name: Next.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Run tests
      run: pnpm run test